### PR TITLE
Classify modules for desktop-usage

### PR DESCRIPTION
**Pull request by DavidS**

### CODE REVIEW

**Comment by pmcmaw** [comment]
Hey @DavidS just wondering if this is something you are still working on or intending to get merged.

**Comment by DavidS** [comment]
I'll push up https://github.com/puppetlabs/iac/pull/206/commits/11d1903fc464ab3c7b794dc96a05d149a385c29d as a new PR - the rest of the work here is superseded by module tiering.

**Comment by DavidS** [comment]
ah - that has already been done in https://github.com/puppetlabs/iac/pull/209

**Comment by pmcmaw** [comment]
thank you :-)

**Pull request closed without merging**
